ceph.py: handle the case where batch_size is None rather than 0
This should resolve

 TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'

Change-Id: I388befe917782b719a154bf12bf5f8127ef5e32e